# Generated by Django 4.1 on 2022-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='Deposit',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='Rent_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='Sale_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
