# Generated by Django 4.1 on 2022-12-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_property_price_property_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='App.profile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='App.profile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='App.profile'),
        ),
    ]
