# Generated by Django 4.1 on 2022-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
